### ISSUE TITLE
implementing hoa-light object

### ISSUE THREAD

**Issue by chikashimiyama** [ZKM-IMA/ZirkoniumSpatializationServer#1]
## Name
 **hoalight** 

## IO 
- [ ] The pd object should have 4 inlets
- [ ] The pd object should have 1 outlet

## Type
- [ ] The pd object is not a DSP object
  
## Inlet
- [ ] The first inlet accepts **bang** / **message**
- [ ] When the first inlet receives a message, starting with "define_loudspeakers" the object interprets the message as a speaker definition formatted in the style of VBAP object and store the data internally
- [ ] The second inlet accepts **float** and it lets the user control the azimuth of the source (-180 ~ 180)
- [ ] The third inlet accepts **float** and it lets the user control the elevation of the source (0 ~ 90)
- [ ] The fourth inlet accepts **float** and it lets the user control the spread (0 ~ 100) 

## processing
- [ ] The pd object internally encodes/decodes higher-order ambisonics using HOA-light library and output the volumes of each speaker when the first inlet receives a bang

## order 
- [ ] The order of ambisonics is defined by the number of speakers automatically

**Comment by danomatika** [comment]
Looks good.

**Comment by chikashimiyama** [comment]
move this issue to pd-externals/hoalight

**Comment by danomatika** [comment]
Transfer keeps failing, I will have to do it manually.
