### ISSUE TITLE
hoa-light object share the speaker definition

### ISSUE THREAD

**Issue by chikashimiyama** [ZKM-IMA/ZirkoniumSpatializationServer#2]
Speaker definition object holds the information of speaker setup. This object is currently only used for vbap but this can be theoretically used also by the hoa-light object

**Comment by danomatika** [comment]
I imagine this may involve changes to the vbap code which allow for exporting and reading the speaker array. Maybe this needs to be done via some sort of getter/setter interface?

**Comment by chikashimiyama** [comment]
moved to

https://github.com/pd-externals/hoalight/issues/11
